version: '3.1'

services:
    api:
        image: com.tookitaki/btc-price-api:latest
        depends_on:
            - database
        ports:
            - 8080:8080

    database:
        image: mariadb
        restart: always
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: admin1
            MYSQL_DATABASE: btc_rates
        volumes:
            - ${PWD}/schema.sql:/var/config/schema.sql
        ports:
            - 3306:3306